website:
  image: kostajh/savaslabs.github.io:master
  command: jekyll serve --config _config.yml,_config.test.yml,_config.dev.yml -H 0.0.0.0 --force_polling --incremental
  restart: on-failure
  ports:
    - "4000:4000"
  volumes:
    - .:/src
