source 'https://rubygems.org'
gem 'github-pages', '>= 195'
gem 'html-proofer'
gem 'travis'
gem 'scss_lint'
gem 'json', github: 'flori/json', branch: 'v1.8'
gem 'mdl'
gem 'jekyll-picture-tag'
gem 'jemoji'
gem 'jekyll-paginate'
gem 'jekyll-twitter-plugin'
gem 'hologram'
gem 'jekyll-seo-tag'
