#!/bin/sh

# Set variables for printing to the command line.
RED='\033[1;31m'
YELLOW='\033[0;33m'
NC='\033[0m'

pass=true

# Run markdown lint (mdl).
mdl=$(bundle exec mdl . -c .mdlrc --git-recurse)
RESULT=$?

# Print mdl errors.
if [ $RESULT != 0 ]; then
	printf "${RED}\nmarkdownlint failed.
${YELLOW}Correct the following markdown errors before committing:\n${NC}"
	echo "$mdl"
	pass=false
fi

# Run proselint on staged markdown and HTML files.
proselint=$(git diff-index --cached HEAD --name-only | grep -E '.md|.html' | xargs proselint)
RESULT=$?

# Print proselint suggestions.
if [ $RESULT != 0 ]; then
    printf "${RED}\nproselint has some suggestions for you.
${YELLOW}You can ignore these suggestions and proceed with your
commit by running git commit with the --no-verify tag.
Don't worry, proselint is a bit picky!\n\n${NC}"
	echo "$proselint\n"
	pass=false
fi

# If there were no failures, proceed with commit.
if $pass; then
	exit 0
fi

exit 1
